# .golangci.yml
# GolangCI-Lint 配置文件 - 适用于现代Go项目

run:
  # 设置超时时间，防止大型项目检查卡死
  timeout: 5m
  # 并发数，0表示自动检测CPU核心数
  concurrency: 4
  # 包含测试文件进行检查
  tests: true

linters:
  # 禁用所有默认linters，只启用我们明确指定的
  default: none
  enable:
    - errcheck      # 检查是否忽略了 error
    - gosimple      # 检查代码是否可以简化（已合并到staticcheck，但保留兼容性）
    - govet         # 官方静态分析工具
    - ineffassign   # 检查无效赋值
    - staticcheck   # 极其强大的静态分析
    - unused        # 检查未使用的变量/常量
    - gocyclo       # 核心：检查函数复杂度 (圈复杂度)
    - revive        # golint 的升级版，检查代码风格
    - bodyclose     # 核心：检查 HTTP Body 是否关闭 (防止内存泄漏)
    - sqlclosecheck # 核心：检查 SQL Rows 是否关闭
    - gosec         # 安全检查
    - misspell      # 拼写错误检查
    - whitespace    # 检查多余的空白字符

linters-settings:
    errcheck:
      # 检查类型断言是否忽略错误
      check-type-assertions: true
      # 检查空白标识符是否忽略错误
      check-blank: true
      # 排除一些常见的可接受的忽略错误的函数
      exclude-functions:
        - io.Copy(*bytes.Buffer)
        - io.Copy(os.Stdout)
        - io.Copy(os.Stderr)
        - (*bytes.Buffer).Write
        - (*strings.Builder).Write
        - (*github.com/gin-gonic/gin.Context).JSON

    gocyclo:
      # 圈复杂度阈值。如果一个函数 `if/else/for` 嵌套太深超过 15，会报错。
      # 这会逼迫你把大函数拆分成小函数，体现架构能力。
      min-complexity: 15

    govet:
      # 启用额外的govet检查
      enable:
        - shadow
        - nilness
        - printf

    revive:
      # 配置revive规则
      rules:
        - name: exported
          arguments:
            - "checkPrivateReceivers" # 检查私有接收者
            - "sayRepetitiveInsteadOfStutters"
        - name: var-naming
          arguments:
            - ["ID", "URL", "HTTP", "HTTPS"]
        - name: line-length-limit
          arguments: [120]
        - name: function-result-limit
          arguments: [3]

    gosec:
      # 排除一些常见的安全检查误报
      excludes:
        - G104  # 不因未处理的错误而失败
        - G304  # 文件路径安全检查（在某些情况下可接受）

    staticcheck:
      # 启用所有检查，但排除一些特定的
      checks:
        - all

issues:
  # 排除不想检查的目录
  exclude-dirs:
    - docs
    - vendor
    - third_party
    - testdata
    - tmp
    - .ans
    - logs
  
  # 排除一些不必太较真的规则
  exclude-rules:
    # 测试文件中排除复杂度和错误检查
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
        - revive
    
    # 排除生成的文件
    - path: \.pb\.go$
      linters:
        - all
    
    - path: docs/docs.go
      linters:
        - all

  # 最大问题数量限制（0表示无限制）
  max-issues-per-linter: 0
  max-same-issues: 0

  # 显示统计信息
  show-stats: true

output:
  # 输出格式
  formats:
    - format: colored-line-number
  # 显示统计信息
  show-stats: true
  print-issued-lines: true
  print-linter-name: true

severity:
  # 默认严重级别
  default-severity: error
  # 特定linters的严重级别
  rules:
    - linters:
        - errcheck
      severity: warning
    - linters:
        - revive
      severity: warning
